# Build: docker build -f Dockerfile.dev .
FROM node:lts-alpine

# Create app directory
WORKDIR '/app'

# Install app dependencies
COPY package*.json tsconfig*.json tailwind.config.js ./

# Install dependencies
RUN npm install 

# Bundle app source
COPY . .

# Expose port
EXPOSE 5173

# Start the app
CMD ["npm", "run", "dev"]